### ISSUE TITLE
Added temporary fix in server/load.json for issue ALAP#197

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AccessPlanningToolProxy#198]
As per issue https://github.com/openBackhaul/AutomatedLinkAcceptanceProxy/issues/197, the equipment uuid is a dependent attribute for framing the attribute inventory/position-of-modem-board, added a temporary fix in server/database/load.json file for retrieving uuid along with cache response. 

Based on decision made on above issue, this fix shall need to be modified.

**Comment by anacabbar** [comment]
This is Issue gets fixed by  [MWDI #917](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/917) and  [MWDI #923](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/923).    

MWDI is now responding as expected, returning the key attributes in the fields-filtered response.
