### ISSUE TITLE
Clarification required in the encoded fields filters in the string-profiles

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AccessPlanningToolProxy#230]
In ALAP(previous version of APTP) , the fields filter are not encoded and in the human readable format in the string-profiles.
For example, to read the ltp-structure , following is the fields filter, 
`logical-termination-point(uuid;server-ltp;client-ltp;layer-protocol(local-id;layer-protocol-name))`
**Inside the code of ALAP , the url encoding was handled and the encoded url will be triggered to MWDI**

In the new version , in the configuration file , the same fields filter is already provided in the encoded format , that is , 
`logical-termination-point%28uuid%3Bserver-ltp%3Bclient-ltp%3Blayer-protocol%28local-id%3Blayer-protocol-name%29%29`

For this new change , providing the following impact for our reference , 
1.	The existing ALAP code that has the url encoding snippet needs to be changed
2.	The fields filter in the string-profile is a configurable field. Incase if someone tries to configure the field manually , it will be little complex to put the encoded fields correctly.
3.	Viewing the fields filter in the encoded format in the configuration file is little difficult than reading it in the human readable format.

**Comment by openBackhaul** [comment]
fields filter strings shall be configured in human readable format in future, too.
The encoding of the values of the respective StringProfiles in the ConfigFile has already been reversed in [branch v1.1.1](https://github.com/openBackhaul/AccessPlanningToolProxy/tree/v1.1.1) .
