### ISSUE TITLE
Clarification in /v1/provide-configuration-for-livenetview 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AccessPlanningToolProxy#231]
For the /v1/provide-configuration-for-livenetview, we have the following callback defined,

- RequestForProvidingConfigurationForLivenetviewCausesDeterminingAirInterfaceUuidUnderTest

But this callback is not available in the configuration file.  Kindly please add this if this is required. Thanks

**Comment by openBackhaul** [comment]
The callback RequestForProvidingConfigurationForLivenetviewCausesDeterminingAirInterface**Uuid**UnderTest is in the OAS, but neither in the ForwardingList, nor in CONFIGfile.
The callback RequestForProvidingConfigurationForLivenetviewCausesDeterminingAirInterfaceUnderTest is in the ForwardingList and in the CONFIGfile, but not in the OAS.
I conclude that this is a typo in the OAS.
I have corrected the name of the callback in the OAS.
This correction is already included in [branch v1.1.1](https://github.com/openBackhaul/AccessPlanningToolProxy/tree/v1.1.1).
