### ISSUE TITLE
Clarification in /v1/provide-status-for-livenetview 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AccessPlanningToolProxy#232]
For the /v1/provide-status-for-livenetview API , we have the following callbacks defined.
But these callbacks are not there in the configuration file , 
RequestForProvidingStatusForLivenetviewCausesDeterminingAirInterfaceUuidUnderTest 
RequestForProvidingStatusForLivenetviewCausesReadingDedicatedStatusFromCache

Also , the Callback RequestForProvidingStatusForLivenetviewCausesReadingDedicatedStatusFromCache is not utilized in formulating the response. So this shall be removed if it is not required. Thanks.

**Comment by openBackhaul** [comment]
It seems there are small typos in the spelling of the callback names in the OAS:
- RequestForProvidingStatusForLivenetviewCausesDeterminingAirInterface**Uuid**UnderTest can be found in ForwardingList and CONFIGfile under RequestForProvidingStatusForLivenetviewCausesDeterminingAirInterfaceUnderTest
- RequestForProvidingStatusForLivenetviewCausesReadingDedicatedStatusFromCache can be found in ForwardingList and CONFIGfile under RequestForProvidingStatusForLivenetviewCausesReadingDedicatedStatusValuesFromLive

OAS has already been corrected in the [branch v1.1.1](https://github.com/openBackhaul/AccessPlanningToolProxy/tree/v1.1.1)
