### ISSUE TITLE
Clarification required regarding storage location of list of connected devices from MWDI

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AccessPlanningToolProxy#233]
As a part of embed-yourself , as a part of the forwarding PromptForEmbeddingCausesCyclicLoadingOfDevicesFromMwdi we are retrieving the list of connected devices from MWDI.
This retrieved information shall be stored in the runtime memory of the application.
Kindly confirm whether this understanding is correct.

**Comment by openBackhaul** [comment]
I am confirming this understanding.
The proxy application does not support permanent data storing in a file or database.

**Comment by PrathibaJee** [comment]
Thank you for the clarification. I will close this issue.
