### ISSUE TITLE
Clarification required in the regular expression for link-id

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AccessPlanningToolProxy#234]
For the link-id , the regular expression pattern is ^\d{3}55\d{4}$
As per my understanding , this means 
\d{3} matches [0-9] exactly 3 times
55 matches the characters 55 literally (case sensitive)
\d{4} matches a digit (equivalent to [0-9])
means , [3 digits]55[4 digits]

For example , the following link ids will be accepted , 
123559876
123556544
but the following will not be , 
123129876
123346544

Kindly please let me know whether the link ids have this restriction because of which we have this "55" hardcoded. (Asking this to understand whether I’m unaware of something)

> on a side note , this pattern of link-id makes a tight coupling and in future there is a change in the link-id format , then APTP application have to be updated accordingly

**Comment by anacabbar** [comment]
The pattern is valid
