### ISSUE TITLE
[Info + Question] Device connection-status information from MWDI 

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/AccessPlanningToolProxy#241]
From MWDI issue https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/980:

> ALAP needs from MWDI:
> Connection-status information of the Mount Points known to the controller (i.e. connected, connecting, unable-to-connect...)
> Notifications of ControllerAttributeValueChanges (i.e. updates about the connected or disconnected devices)

1. MWDI release 1.2.0 will offer service /v1/provide-device-status-metadata which contains the connection status.
2. Controller attribute value changes:
    - the MWDI currently does not offer notifications about connection-status changes at the controller
    - the APTP could however subscribe at the NotificationProxy (NP) for that information (see as an example the MWDI service "/v1/regard-controller-attribute-value-change", which is used to receive subscriptions from the NP)
 

@anacabbar: please check, if it would suffice for the APTP to subscribe at the NotificationProxy or if the MWDI really needs to offer that functionality as well.

**Comment by anacabbar** [comment]
Receiving notifications about "Controller Value Changes" directly from the NotificationProxy should suffice.

**Comment by anacabbar** [comment]
If **/v1/provide-device-status-metadata** provides the list of all known mount points with corresponding connection-status, for the APTP, subscribing at NP for ControllerAttrivuteValueChanges should suffice.

But for understanding purposes, I see MWDI does offer services for other subscriptions (i.e. AttributeValueChanges at device-level, object creations/deletions). Was there a motiviation to offer these subscriptions, which is missing for offering subscriptions at controller level?
